[status]
separator_open = ""
separator_close = ""
mode_normal = {bg = "reset", fg = "blue" , bold = true , reversed = true}
mode_select = {bg = "reset", fg = "red" , bold = true , reversed = true}
mode_unset = {bg = "reset", fg = "red" , bold = true , reversed = true}
separator_style = {bg = "reset", fg = "gray", reversed = true}

[icon]
prepend_rules = [
  { name = "*.org", text = "", fg = "#78ac9a"},
  { name = "*.tex", text = "", fg = "#ffffff"},
  { name = "*.blend", text = "󰂫", fg = "#e87d0d"},
  { name = "Makefile", text = "", fg = "#ffffff"},
  { name = "go.mod", text = "", fg = "#ffffff"},
  { name = "go.sum", text = "", fg = "#ffffff"},
  { name = "*.prof", text = "", fg = "#ffffff"},
  { name = "*.asm", text = "", fg = "#405ba9"},
  { name = "*", text = "e", is = "exec", fg = "#ffffff"}
]
