UP add volume 10
DOWN add volume -10
Ctrl+UP add volume 1
Ctrl+DOWN add volume -1
WHEEL_UP add volume 2
WHEEL_DOWN add volume -2
Shift+g add sub-scale +0.01
Shift+f add sub-scale -0.01
] add chapter 1
[ add chapter -1
- multiply speed 1/1.1
+ multiply speed 1.1
Ctrl+RIGHT seek 60
Ctrl+LEFT seek -60
v cycle sub
V cycle sub down
b cycle audio
B cycle audio down

