--screenshot-directory=~/Pictures/mpv-screenshots
--screenshot-template=mpv-shot-%F-%P
--screenshot-format=png
--keep-open=yes
[default]

[av1]
vd-queue-enable=yes
ad-queue-enable=yes
vd-queue-max-bytes=6000MiB
vd-queue-max-samples=2000000
vd-queue-max-secs=50
cache=yes
demuxer-max-bytes=2000M
demuxer-max-back-bytes=1000M
